# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20190513_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_image',
            field=models.ImageField(null=True, upload_to='my-pics/'),
        ),
    ]
